In [1]:
import tensorflow as tf
import string
import requests
import pandas as pd

In [2]:
response = requests.get('https://raw.githubusercontent.com/laxmimerit/poetry-data/master/adele.txt')

In [40]:
# response

In [41]:
# response.text

In [42]:
data=response.text.splitlines()
print(data[:10]) # 10 sample

['Looking for some education', 'Made my way into the night', 'All that bullshit conversation', "Baby, can't you read the signs? I won't bore you with the details, baby", "I don't even wanna waste your time", "Let's just say that maybe", 'You could help me ease my mind', "I ain't Mr. Right But if you're looking for fast love", "If that's love in your eyes", "It's more than enough"]


In [43]:
len(data)
#there is 2400 lines in this poetry

2400

In [44]:
# Total word number is:
len(" ".join(data))

91330

In [8]:
import numpy as np
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, LSTM, Embedding, Dropout, Conv1D, MaxPooling1D
from tensorflow.keras.preprocessing.sequence import pad_sequences


#### LSTM model and train test preparation

In [9]:
tokenizer=Tokenizer()
tokenizer.fit_on_texts(data) #it's going to fit on the data in the forms of lines.

In [45]:
# help(tokenizer)

In [48]:
encoded_text=tokenizer.texts_to_sequences(data)
encoded_text[:10]
# These number actually comes from vocabulary
# it assigns number to each words

[[254, 21, 219, 725],
 [117, 8, 80, 153, 3, 133],
 [14, 10, 726, 727],
 [41, 56, 2, 603, 3, 728, 1, 68, 517, 2, 40, 3, 518, 41],
 [1, 23, 107, 189, 300, 9, 57],
 [286, 35, 46, 10, 230],
 [2, 83, 134, 4, 519, 8, 120],
 [1, 37, 520, 102, 19, 27, 25, 254, 21, 328, 11],
 [27, 209, 11, 13, 9, 124],
 [42, 67, 210, 125]]

In [51]:
wc=tokenizer.word_counts
# word frequency

In [52]:
wi=tokenizer.word_index

In [53]:
print(f"Number of unique words and total vocab size: {len(tokenizer.word_counts)+1}")
vocab_size=len(tokenizer.word_counts)+1 # always adding plus one for tensorflow

Number of unique words and total vocab size: 1396


In [15]:
x=["play this song"]

In [16]:
tokenizer.texts_to_sequences(x)

[[241, 44, 409]]

### Prepare data for training

In [54]:
 encoded_text[:10] # 10 sample

[[254, 21, 219, 725],
 [117, 8, 80, 153, 3, 133],
 [14, 10, 726, 727],
 [41, 56, 2, 603, 3, 728, 1, 68, 517, 2, 40, 3, 518, 41],
 [1, 23, 107, 189, 300, 9, 57],
 [286, 35, 46, 10, 230],
 [2, 83, 134, 4, 519, 8, 120],
 [1, 37, 520, 102, 19, 27, 25, 254, 21, 328, 11],
 [27, 209, 11, 13, 9, 124],
 [42, 67, 210, 125]]

In [55]:
data_list=[]
for i in encoded_text:
    if len(i)>1:
        for j in range(2,len(i)):
            data_list.append(i[:j])
#             print(i[:j]) # if you want to check data

#### Paddding

In [19]:
max_length=20
#max length of line is 20 token per line in our poetry

In [58]:
sequences=pad_sequences(data_list,maxlen=max_length,padding="pre") # we set the lenght size equal to 20
sequences[:5] # 5 sample

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 254,  21],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 254,  21, 219],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0, 117,   8],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0, 117,   8,  80],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0, 117,   8,  80, 153]])

In [59]:
sequences.shape

(14231, 20)

In [61]:
X=sequences[:,:-1]
y=sequences[:,-1]
print("X values")
print(X[:5]) # 5 sample
print("-"*30)
print("X values")
print(y[:5]) # 5 sample

X values
[[  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  254]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 254
   21]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
  117]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 117
    8]
 [  0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0 117   8
   80]]
------------------------------
X values
[ 21 219   8  80 153]


In [23]:
X.shape,y.shape

((14231, 19), (14231,))

In [62]:
y=to_categorical(y,num_classes=vocab_size)
#since unique word number is vocab_size, thus there is vocab_size classes
print(y[:5]) # 5 sample
print("Shape of y",y.shape)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Shape of y (14231, 1396)


In [63]:
print("Shape of X",X.shape)
seq_length=X.shape[1]
seq_length

Shape of X (14231, 19)


19

#### Build Model
- We will build a simple LSTM model

In [26]:
model=Sequential()
model.add(Embedding(vocab_size,50,input_length=seq_length)) 
#The first layer is the Embedded layer that uses 50-length vectors
#return_sequences=True because we add another LSTM
model.add(LSTM(100,return_sequences=True))
model.add(LSTM(100))
model.add(Dense(100,activation="relu"))
model.add(Dense(vocab_size,activation="softmax")) # we use softmax because there is multiclasses

In [27]:
# help(Embedding)

#### You can use dropout() , You will see that Training will be slightly slower trend in convergence, maybe lower final accuracy

In [28]:
# model=Sequential()
# model.add(Embedding(vocab_size,50,input_length=seq_length)) 
# #The first layer is the Embedded layer that uses 50-length vectors
# #return_sequences=True because we add another LSTM
# model.add(Dropout(0.2))
# model.add(LSTM(100,return_sequences=True))
# model.add(Dropout(0.2))
# model.add(LSTM(100))
# model.add(Dropout(0.2))
# model.add(Dense(100,activation="relu"))
# model.add(Dense(vocab_size,activation="softmax")) # we use softmax because there is multiclasses

####  Dropout can be applied to the input and recurrent connections of the memory units with the LSTM precisely and separately.
#### LSTM-specific dropout may have more pronounced effect on the convergence of the network than the layer-wise dropout.

In [29]:
# model=Sequential()
# model.add(Embedding(vocab_size,50,input_length=seq_length)) 
# #The first layer is the Embedded layer that uses 50-length vectors
# #return_sequences=True because we add another LSTM
# model.add(LSTM(100,return_sequences=True,dropout=0.2,recurrent_dropout=0.2))
# model.add(LSTM(100,dropout=0.2,recurrent_dropout=0.2))
# model.add(Dense(100,activation="relu"))
# model.add(Dense(vocab_size,activation="softmax")) # we use softmax because there is multiclasses

#### LSTM and CNN can be used together

In [30]:
# model=Sequential()
# model.add(Embedding(vocab_size,50,input_length=seq_length)) 
# #The first layer is the Embedded layer that uses 50-length vectors
# #return_sequences=True because we add another LSTM
# model.add(Conv1D(filters=32,kernel_size=3, padding="same",activation="relu"))
# model.add(MaxPooling1D(pool_size=2))
# model.add(LSTM(100,return_sequences=True))
# model.add(LSTM(100))
# model.add(Dense(100,activation="relu"))
# model.add(Dense(vocab_size,activation="softmax")) # we use softmax because there is multiclasses

In [31]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 19, 50)            69800     
                                                                 
 lstm (LSTM)                 (None, 19, 100)           60400     
                                                                 
 lstm_1 (LSTM)               (None, 100)               80400     
                                                                 
 dense (Dense)               (None, 100)               10100     
                                                                 
 dense_1 (Dense)             (None, 1396)              140996    
                                                                 
Total params: 361,696
Trainable params: 361,696
Non-trainable params: 0
_________________________________________________________________


In [32]:
model.compile(loss="categorical_crossentropy",optimizer="adam",metrics=["accuracy"])

In [33]:
model.fit(X,y,batch_size=32,epochs=150)

Epoch 1/150
445/445 [==============================] - 17s 29ms/step - loss: 5.6915 - accuracy: 0.0400
Epoch 2/150
445/445 [==============================] - 14s 31ms/step - loss: 5.2304 - accuracy: 0.0522
Epoch 3/150
445/445 [==============================] - 13s 30ms/step - loss: 5.0358 - accuracy: 0.0628
Epoch 4/150
445/445 [==============================] - 14s 32ms/step - loss: 4.8863 - accuracy: 0.0734
Epoch 5/150
445/445 [==============================] - 13s 29ms/step - loss: 4.7719 - accuracy: 0.0828
Epoch 6/150
445/445 [==============================] - 12s 27ms/step - loss: 4.6617 - accuracy: 0.0948
Epoch 7/150
445/445 [==============================] - 13s 28ms/step - loss: 4.5568 - accuracy: 0.0993
Epoch 8/150
445/445 [==============================] - 13s 28ms/step - loss: 4.4429 - accuracy: 0.1119
Epoch 9/150
445/445 [==============================] - 12s 28ms/step - loss: 4.3251 - accuracy: 0.1254
Epoch 10/150
445/445 [==============================] - 13s 29ms/step - l

445/445 [==============================] - 12s 28ms/step - loss: 0.9798 - accuracy: 0.7465
Epoch 80/150
445/445 [==============================] - 13s 28ms/step - loss: 0.9668 - accuracy: 0.7496
Epoch 81/150
445/445 [==============================] - 12s 28ms/step - loss: 0.9541 - accuracy: 0.7516
Epoch 82/150
445/445 [==============================] - 12s 28ms/step - loss: 0.9408 - accuracy: 0.7531
Epoch 83/150
445/445 [==============================] - 12s 28ms/step - loss: 0.9292 - accuracy: 0.7557
Epoch 84/150
445/445 [==============================] - 12s 28ms/step - loss: 0.9143 - accuracy: 0.7576
Epoch 85/150
445/445 [==============================] - 12s 28ms/step - loss: 0.9059 - accuracy: 0.7600
Epoch 86/150
445/445 [==============================] - 12s 28ms/step - loss: 0.8895 - accuracy: 0.7635
Epoch 87/150
445/445 [==============================] - 12s 28ms/step - loss: 0.8974 - accuracy: 0.7623
Epoch 88/150
445/445 [==============================] - 12s 28ms/step - loss:

### Text Generation

In [34]:
text_lenght= 15 # 15 words per line

def generate_text(input_text, no_lines):
    general_text=[]
    for i in range(no_lines):
        text=[]
        for _ in range(text_lenght):
            encoded=tokenizer.texts_to_sequences([input_text])
            encoded=pad_sequences(encoded,maxlen=seq_length,padding="pre")
            y_pred=np.argmax(model.predict(encoded),axis=-1) # it will generate a word index, loop up into dictionary containing word index
            
            predicted_word=""
            for word,index in tokenizer.word_index.items():
                if index==y_pred:
                    predicted_word=word
                    break
                    
            input_text=input_text +' '+ predicted_word
            text.append(predicted_word)
        
        input_text=text[-1]
        text=" ".join(text) # input text will be the last word of first created line
        general_text.append(text)
    
    return general_text

In [35]:
input_text="me"
text_produced=generate_text(input_text,6)
text_produced

1/1 [==============================] - 0s 20ms/step


["by the seams no bribing me to doubt and i'll do do i never knew",
 'believe is a memory i can tell by the way you walk that the air',
 "she gave you things i didn't give to you old friend why are you so",
 'i spend my whole life hiding my heart away away woke up feeling heavy the',
 "last time let it lose hold me in won't out can you prefer the morning",
 "t show emotions don t know just a place in you and you're in my"]

In [36]:
input_text="i want to see you"
text_produced=generate_text(input_text,6)
text_produced

1/1 [==============================] - 0s 21ms/step


['were away its hole you go at the world town steady as she goes so',
 'i spend my whole life hiding my heart away away woke up feeling heavy the',
 "last time let it lose hold me in won't out can you prefer the morning",
 "t show emotions don t know just a place in you and you're in my",
 'god this reminds so give me till that i went on home to my been',
 "that scares me the more eager i will always still but i know that's where"]

In [ ]:
input_text="i want to see you"
text_produced=generate_text(input_text,6)
text_produced